name: Dev deployment 

on:
    push:
        branches:
            - dev


jobs:
    install-build-application:
        name: Install and Build the application
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build App artifacts using pnpm
              uses: pnpm/action-setup@v4
            - run: |
                echo API_BASE_URL="${{ vars.DEV_API_BASE_URL }}" >> .env
                echo CMS_EMAIL="${{ secrets.DEV_CMS_EMAIL }}" >> .env
                echo CMS_PASSWORD="${{ secrets.DEV_CMS_PASSWORD }}" >> .env
                echo FIREBASE_API_KEY="${{ secrets.DEV_FIREBASE_API_KEY }}" >> .env
                echo FIREBASE_AUTH_DOMAIN="${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}" >> .env
                echo FIREBASE_PROJECT_ID="${{ secrets.DEV_FIREBASE_PROJECT_ID }}" >> .env
                echo FIREBASE_STORAGE_BUCKET="${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}" >> .env
                echo FIREBASE_MESSAGING_SENDER_ID="${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
                echo FIREBASE_APP_ID="${{ secrets.DEV_FIREBASE_APP_ID }}" >> .env
                echo STRIPE_PUBLISHABLE_KEY="${{ secrets.DEV_STRIPE_PUBLISHABLE_KEY }}" >> .env
                echo NUXT_PUBLIC_JWPLAYER_KE="${{ secrets.DEV_NUXT_PUBLIC_JWPLAYER_KE }}" >> .env
                echo NUXT_PUBLIC_JWPLAYER_LIBRARY_UR="${{ secrets.DEV_NUXT_PUBLIC_JWPLAYER_LIBRARY_UR }}" >> .env
                echo NUXT_PUBLIC_JWPLAYER_DEVMODE="${{ vars.DEV_NUXT_PUBLIC_JWPLAYER_DEVMODE }}" >> .env
                echo NUXT_PUBLIC_JWPLAYER_DEVMODE_DEMO_LIBRARY_URL="${{ secrets.DEV_NUXT_PUBLIC_JWPLAYER_DEVMODE_DEMO_LIBRARY_UR }}" >> .env
                echo GOOGLE_CLIENT_ID="${{ secrets.DEV_GOOGLE_CLIENT_ID }}" >> .env
                echo GOOGLE_CLIENT_SECRET="${{ secrets.DEV_GOOGLE_CLIENT_SECRET }}" >> .env
                touch .env
                pnpm install
                pnpm run build
                tar -czf output.tar.gz .output
            - name: Store app artifacts for distribution
              uses: actions/upload-artifact@v4
              with:
                name: app-artifacts
                path: output.tar.gz

    deploy-application:
        needs: install-build-application
        name: Prepare release on server
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: app-artifacts
            - name: Upload app-artifacts
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.DEV_SERVER_SSH_HOST }}
                port: ${{ secrets.DEV_SERVER_SSH_PORT }}
                username: ${{ secrets.DEV_SERVER_SSH_USER }}
                key: ${{ secrets.DEV_SERVER_SSH_KEY }}
                source: output.tar.gz
                target: ${{ vars.DEV_ARTIFACT_DIR }}

            - name: Extract archive and create directories
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.DEV_SERVER_SSH_HOST }}
                port: ${{ secrets.DEV_SERVER_SSH_PORT }}
                username: ${{ secrets.DEV_SERVER_SSH_USER }}
                key: ${{ secrets.DEV_SERVER_SSH_KEY }}
                script: |
                    cd ${{ vars.DEV_APP_DIR }}
                    git pull --autostash
                    echo "Renaming existing .output folder to .output_old"
                    mv .output .output_$(date +%Y%m%d%H%M%S)
                    tar -xzf ${{ vars.DEV_ARTIFACT_DIR }}/output.tar.gz -C ${{ vars.DEV_APP_DIR }}/
                    rm ${{ vars.DEV_ARTIFACT_DIR }}/output.tar.gz
                    pm2 restart ${{ vars.DEV_PM2_SL }}
